DROP SCHEMA IF EXISTS `ACHIEVEMENT_TRACKER`;

CREATE SCHEMA `ACHIEVEMENT_TRACKER`;

USE `ACHIEVEMENT_TRACKER`;

CREATE TABLE `GAME` (
    `STORE_ID` BIGINT NOT NULL,
    `STEAM_APP_ID` BIGINT NOT NULL,
    `TITLE` VARCHAR(200) NOT NULL,
    `RELEASE_DATE` DATE NULL,
    `COMING_SOON` TINYINT(1) NOT NULL,
    `SHORT_DESCRIPTION` TEXT NOT NULL,
    `LONG_DESCRIPTION` TEXT NOT NULL,
    `HEADER_IMAGE` VARCHAR(100) NOT NULL,
    `CAPSULE_IMAGE` VARCHAR(100) NOT NULL,
    `CAPSULE_SMALL_IMAGE` VARCHAR(100) NOT NULL,
    `BACKGROUND_IMAGE` VARCHAR(100) NOT NULL,
    `BACKGROUND_RAW_IMAGE` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`STORE_ID`));

CREATE TABLE `ACHIEVEMENT` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(125) NOT NULL,
    `DISPLAY_NAME` TEXT NOT NULL,
    `DESCRIPTION` TEXT NULL,
    `HIDDEN` TINYINT(1) NOT NULL,
    `ICON` VARCHAR(125) NOT NULL,
    `ICON_GRAY` VARCHAR(125) NOT NULL,
    `PERCENTAGE` DECIMAL(5,2) NOT NULL,
    `GAME_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`),
    INDEX `FK_GAME_IDX` (`GAME_ID` ASC) VISIBLE,
    CONSTRAINT `FK_GAME` FOREIGN KEY (`GAME_ID`)
        REFERENCES `GAME` (`STORE_ID`)
        ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE `CATEGORY` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(45) UNIQUE NOT NULL,
    `POPULARITY` INT NOT NULL, 
    PRIMARY KEY (`ID`));

CREATE TABLE `GAME_CATEGORY` (
    `GAME_ID` BIGINT NOT NULL,
    `CATEGORY_ID` BIGINT NOT NULL,
    `VOTES` INT NOT NULL,
    INDEX `FK_GAME_IDX` (`GAME_ID` ASC) VISIBLE,
    INDEX `FK_CATEGORY_IDX` (`CATEGORY_ID` ASC) VISIBLE,
    CONSTRAINT `FK_GAME_TO_CATEGORY` FOREIGN KEY (`GAME_ID`)
        REFERENCES `GAME` (`STORE_ID`)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK_CATEGORY_TO_GAME` FOREIGN KEY (`CATEGORY_ID`)
        REFERENCES `CATEGORY` (`ID`)
        ON DELETE CASCADE ON UPDATE CASCADE);